# rabbit的配置信息
spring:
  rabbitmq:
    # RabbitMQ的IP地址
    host: 172.16.248.130
    # RabbitMQ的通信端口
    port: 5672
    # RabbitMQ的用户名
    username: rabbit
    # RabbitMQ的密码
    password: rabbit
    # 虚拟主机
    virtual-host: dev
    # 监听参数配置
    listener:
      simple:
        # 每次只能获取一条消息，处理完成才能获取下一个消息 这样消费预取限制（轮着分配完后在消费）
        prefetch: 1
        # 消息者确认机制 none，关闭ack；manual 手动ack；auto 自动ack
        # 建议配置auto和重试与失败处理策略
        acknowledge-mode: auto
        retry:
          enabled: true
          # 最大重试3次
          max-attempts: 3
          # 下次失败等待时长倍数 下次等待时长 = multiplier*initial-interval
          multiplier: 1
          # 初始失败等待时间单位毫秒
          initial-interval: 10000ms
          # true 无装态 false 有状态 如果中包含事务这里就要改为false
          stateless: true
