# rabbit的配置信息
spring:
  rabbitmq:
    # RabbitMQ的IP地址
    host: 172.16.248.130
    # RabbitMQ的通信端口
    port: 5672
    # RabbitMQ的用户名
    username: rabbit
    # RabbitMQ的密码
    password: rabbit
    # 虚拟主机
    virtual-host: dev
    # 监听参数配置
    listener:
      simple:
        # 每次只能获取一条消息，处理完成才能获取下一个消息 这样消费预取限制（轮着分配完后在消费）
        prefetch: 1