# 配置
spring:
  # nacos 服务注册中心
  cloud:
    nacos:
      server-addr: http://172.16.248.130:8848
      # nacos 动态指定空间配置
      config:
        namespace: ${spring.profiles.active:public}
        # nacos 配置中心参数关闭检察吂动才不会报错
        import-check:
          enabled: false
  # 配置中心导入配置
  config:
    # nacos dataId 外部优先本地配置 先申明优先
    import:
      - nacos:base.properties?group=service-order
      - nacos:common.properties?group=service-order
      - haha.properties?group=service-order
    # nacos 配置中心 指定加的空间配置数据集 用来表示环境信息
    activate:
      on-profile: ${spring.profiles.active:pro}


# 服务端口
server:
  port: 9000

logging:
  config: classpath:log4j2.xml

# 1 多环境定义在一个yml中时 必须用 --- 来分割
# 2 定义在多个配置文件中
#sit env 加载数据集 默认配置文件 application.yaml；任何时候都会加载指定环境配置文件 application-{env}.yaml
#
#---
# pro env 加载数据集
#spring:
#  config:
#    import:
#      - nacos:base.properties?group=service-order
#      - nacos:common.properties?group=service-order
#     - hello.properties?group=service-order
#    activate:
#      on-profile: pro