# 服务名称
spring:
  application:
    name: service-order
  # nacos 服务注册中心
  cloud:
    nacos:
      server-addr: http://172.16.248.130:8848

# 服务端口
server:
  port: 9000

logging:
  config: classpath:log4j2.xml

